gyros_arch_srcs = list(map(File, [ 'debug.c',
                                   'init.c',
                                   'interrupt.c',
                                   'pendsv.S',
                                   'stack_used.c' ]))

Return("gyros_arch_srcs")
