gyros_arch_srcs = map(File, [ 'debug.c',
                              'init.c',
                              'interrupt.c',
                              'stack_used.c',
                              'task_init.c' ])

Return("gyros_arch_srcs")
