gyros_arch_srcs = list(map(File, [ 'debug.c',
                                   'stack_used.c',
                                   'task_init.c' ]))

gyros_arch_arm_srcs = list(map(File, [ 'interrupt.c', 'interrupt2.c' ]))

Return("gyros_arch_srcs", "gyros_arch_arm_srcs")
