Import("target_env")
try:
    Import("target_arm_env")
except:
    target_arm_env = target_env

######################################################################
# Common source files
######################################################################
common_srcs = SConscript('../../src/SConscript')

######################################################################
# Target specific source files
######################################################################
srcs = common_srcs + [ 'exceptions.S',
                       '../arm/stack_used.c',
                       '../arm/task_init.c',
                       'idle.c',
                       'init.c',
                       'interrupt.c' ]

arm_objs = target_arm_env.StaticObject('../arm/interrupt.c')

######################################################################
# Library target
######################################################################
Default(target_env.StaticLibrary('gyros-at91sam7s', srcs + arm_objs))
