Import("target_env")
try:
    Import("target_arm_env")
except:
    target_arm_env = target_env

######################################################################
# Common source files
######################################################################
common_srcs = SConscript('../../src/SConscript')

######################################################################
# Target specific source files
######################################################################
srcs = common_srcs + [ 'exceptions.S',
                       '../arm/stack_used.c',
                       '../arm/task_init.c',
                       'init.c',
                       'interrupt.c']

arm_objs = map(target_arm_env.StaticObject, ['../arm/interrupt.c',
                                             'idle.c'])

######################################################################
# Library target
######################################################################
Default(target_env.StaticLibrary('gyros-str91x', srcs + arm_objs))
