Import("*")

gyros_common_srcs = map(target_env.File, [ 'cond.c',
                                           'current.c',
                                           'debug.c',
                                           'delete.c',
                                           'iterate.c',
                                           'mutex.c',
                                           'priority.c',
                                           'rwlock.c',
                                           'sem.c',
                                           'sleep.c',
                                           'suspend.c',
                                           'task.c',
                                           'timeout.c',
                                           'udelay.c',
                                           'wait.c',
                                           'yield.c' ])

Return("gyros_common_srcs")
