Import("*")

gyros_srcs = map(target_env.File, [ 'task.c', 'delete.c', 'current.c',
                                    'lock.c', 'suspend.c', 'sleep.c', 'wait.c',
                                    'mutex.c', 'cond.c', 'sem.c',
                                    'iterate.c' ])

Export("gyros_srcs")

SConscript(['target/SConscript'])
